package de.larsgrefer.sass.gradle;

import com.palantir.javapoet.*;
import lombok.Data;
import org.gradle.api.DefaultTask;
import org.gradle.api.file.ConfigurableFileCollection;
import org.gradle.api.file.DirectoryProperty;
import org.gradle.api.tasks.*;
import org.yaml.snakeyaml.Yaml;

import javax.lang.model.element.Modifier;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;

@CacheableTask
public abstract class GenerateDeprecations extends DefaultTask {

    @PathSensitive(PathSensitivity.NONE)
    @InputFiles
    public abstract ConfigurableFileCollection getInputFiles();

    @OutputDirectory
    public abstract DirectoryProperty getGeneratedSourcesDir();

    @SuppressWarnings("NewApi")
    @TaskAction
    public void generateDeprecations() throws IOException {

        TypeSpec.Builder enumBuilder = TypeSpec.enumBuilder("Deprecation");

        ClassName dartSassDeprecationStatus = ClassName.bestGuess("DartSassDeprecationStatus");
        enumBuilder
                .addJavadoc("@implNote This class is generated by $L\n", GenerateDeprecations.class)
                .addJavadoc("""
                        @see <a href="https://github.com/sass/sass/blob/main/spec/deprecations.yaml">https://github.com/sass/sass/blob/main/spec/deprecations.yaml</a>
                        @author Lars Grefer""")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(ClassName.bestGuess("lombok.Getter"))
                .addAnnotation(ClassName.bestGuess("lombok.RequiredArgsConstructor"))
                .addField(String.class, "id", Modifier.PRIVATE, Modifier.FINAL)
                .addField(FieldSpec.builder(String.class, "description", Modifier.PRIVATE, Modifier.FINAL)
                        .addJavadoc("$L", "One-line description of this deprecation.")
                        .build())
                .addField(FieldSpec.builder(dartSassDeprecationStatus, "status", Modifier.PRIVATE, Modifier.FINAL)
                        .addJavadoc("$L", "Status of this deprecation in Dart Sass")
                        .build())
                .addField(FieldSpec.builder(String.class, "deprecated", Modifier.PRIVATE, Modifier.FINAL)
                        .addJavadoc("$L", "Dart Sass version that deprecated this feature.")
                        .build())
                .addField(FieldSpec.builder(String.class, "obsolete", Modifier.PRIVATE, Modifier.FINAL)
                        .addJavadoc("$L", "Dart Sass version that obsoleted this deprecation.")
                        .build());

        Map<String, DeprecationDto> deprecations = loadDeprecations();

        deprecations.forEach((id, deprecationDto) -> {
            getLogger().warn("Loaded deprecation: {} -> {}", id, deprecationDto);

            String enumName = id.toUpperCase().replace("-", "_");
            enumBuilder.addEnumConstant(enumName, TypeSpec
                    .anonymousClassBuilder("$S,\n$S,\n$L.$L,\n$S,\n$S", id,
                            deprecationDto.getDescription(),
                            dartSassDeprecationStatus, deprecationDto.getDartSassStatus().toUpperCase(Locale.ROOT),
                            deprecationDto.getDartSassDeprecated(),
                            deprecationDto.getDartSassObsolete())
                    .addJavadoc("$L", deprecationDto.getDescription())
                    .addJavadoc("\n\n")
                    .addJavadoc("@see <a href=\"https://sass-lang.com/d/$L\">$L</a>\n", id, id)
                    .addJavadoc("@since dart-sass $L", deprecationDto.dartSassDeprecated)
                    .build());

        });

        enumBuilder.addMethod(MethodSpec.methodBuilder("find")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .addParameter(String.class, "id")
                .beginControlFlow("if (id == null)")
                .addStatement("return null")
                .endControlFlow()
                .beginControlFlow("for (Deprecation deprecation : values())")
                .beginControlFlow("if (deprecation.getId().equals(id))")
                .addStatement("return deprecation")
                .endControlFlow()
                .endControlFlow()
                .addStatement("return null")
                .returns(ClassName.bestGuess("Deprecation"))
                .build());

        enumBuilder.addMethod(MethodSpec.methodBuilder("getDocumentationLink")
                .addModifiers(Modifier.PUBLIC)
                .addStatement("return String.format($S, id)", "https://sass-lang.com/d/%s")
                .returns(String.class)
                .build());


        JavaFile javaFile = JavaFile.builder("de.larsgrefer.sass.spec", enumBuilder.build()).build();

        javaFile.writeTo(getGeneratedSourcesDir().get().getAsFile());
    }

    private File getDeprecationsFile() {
        return getInputFiles().filter(file -> file.getName().endsWith(".yml") || file.getName().endsWith(".yaml")).getSingleFile();
    }

    @SuppressWarnings("NewApi")
    private Map<String, DeprecationDto> loadDeprecations() throws IOException {
        Map<String, DeprecationDto> result = new LinkedHashMap<>();

        try (InputStream inputStream = Files.newInputStream(getDeprecationsFile().toPath())) {
            Map<String, ?> map = new Yaml().loadAs(inputStream, Map.class);

            map.forEach((id, v) -> {
                DeprecationDto deprecationDto = new DeprecationDto();
                deprecationDto.setId(id);

                Map<String, ?> data = (Map<String, ?>) v;
                deprecationDto.setDescription(data.get("description").toString());

                Map<String, String> dartSass = (Map<String, String>) data.get("dart-sass");
                deprecationDto.setDartSassStatus(dartSass.get("status"));
                deprecationDto.setDartSassDeprecated(dartSass.get("deprecated"));
                deprecationDto.setDartSassObsolete(dartSass.get("obsolete"));

                result.put(id, deprecationDto);
            });

        }

        return result;
    }

    @Data
    public static class DeprecationDto {
        private String id;
        private String description;

        private String dartSassStatus;
        private String dartSassDeprecated;
        private String dartSassObsolete;
    }
}
