package de.larsgrefer.sass.gradle;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.palantir.javapoet.*;
import lombok.Data;
import org.gradle.api.DefaultTask;
import org.gradle.api.file.DirectoryProperty;
import org.gradle.api.file.RegularFileProperty;
import org.gradle.api.tasks.*;
import tools.jackson.core.type.TypeReference;
import tools.jackson.dataformat.yaml.YAMLMapper;

import javax.lang.model.element.Modifier;
import java.io.File;
import java.io.IOException;
import java.util.Locale;
import java.util.Map;

@CacheableTask
public abstract class GenerateDeprecations extends DefaultTask {

    @PathSensitive(PathSensitivity.NONE)
    @InputFile
    public abstract RegularFileProperty getDeprecationsYamlFile();

    @OutputDirectory
    public abstract DirectoryProperty getGeneratedSourcesDir();

    @SuppressWarnings("NewApi")
    @TaskAction
    public void generateDeprecations() throws IOException {

        TypeSpec.Builder enumBuilder = TypeSpec.enumBuilder("Deprecation");

        ClassName dartSassDeprecationStatus = ClassName.bestGuess("DartSassDeprecationStatus");
        enumBuilder
                .addJavadoc("@implNote This class is generated by $L\n", GenerateDeprecations.class)
                .addJavadoc("""
                        @see <a href="https://github.com/sass/sass/blob/main/spec/deprecations.yaml">https://github.com/sass/sass/blob/main/spec/deprecations.yaml</a>
                        @author Lars Grefer""")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(ClassName.bestGuess("lombok.Getter"))
                .addAnnotation(ClassName.bestGuess("lombok.RequiredArgsConstructor"))
                .addField(String.class, "id", Modifier.PRIVATE, Modifier.FINAL)
                .addField(FieldSpec.builder(String.class, "description", Modifier.PRIVATE, Modifier.FINAL)
                        .addJavadoc("$L", "One-line description of this deprecation.")
                        .build())
                .addField(FieldSpec.builder(dartSassDeprecationStatus, "status", Modifier.PRIVATE, Modifier.FINAL)
                        .addJavadoc("$L", "Status of this deprecation in Dart Sass")
                        .build())
                .addField(FieldSpec.builder(String.class, "deprecated", Modifier.PRIVATE, Modifier.FINAL)
                        .addJavadoc("$L", "Dart Sass version that deprecated this feature.")
                        .build())
                .addField(FieldSpec.builder(String.class, "obsolete", Modifier.PRIVATE, Modifier.FINAL)
                        .addJavadoc("$L", "Dart Sass version that obsoleted this deprecation.")
                        .build());

        Map<String, DeprecationDto> deprecations = loadDeprecations();

        deprecations.forEach((id, deprecationDto) -> {
            getLogger().info("Loaded deprecation: {} -> {}", id, deprecationDto);

            String enumName = id.toUpperCase().replace("-", "_");
            enumBuilder.addEnumConstant(enumName, TypeSpec
                    .anonymousClassBuilder("$S,\n$S,\n$L.$L,\n$S,\n$S", id,
                            deprecationDto.getDescription(),
                            dartSassDeprecationStatus, deprecationDto.getDartSass().getStatus().toUpperCase(Locale.ROOT),
                            deprecationDto.getDartSass().getDeprecated(),
                            deprecationDto.getDartSass().getObsolete())
                    .addJavadoc("$L", deprecationDto.getDescription())
                    .addJavadoc("\n\n")
                    .addJavadoc("@see <a href=\"https://sass-lang.com/d/$L\">$L</a>\n", id, id)
                    .addJavadoc("@since dart-sass $L", deprecationDto.getDartSass().getDeprecated())
                    .build());

        });

        enumBuilder.addMethod(MethodSpec.methodBuilder("find")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .addParameter(String.class, "id")
                .beginControlFlow("if (id == null)")
                .addStatement("return null")
                .endControlFlow()
                .beginControlFlow("for (Deprecation deprecation : values())")
                .beginControlFlow("if (deprecation.getId().equals(id))")
                .addStatement("return deprecation")
                .endControlFlow()
                .endControlFlow()
                .addStatement("return null")
                .returns(ClassName.bestGuess("Deprecation"))
                .build());

        enumBuilder.addMethod(MethodSpec.methodBuilder("getDocumentationLink")
                .addModifiers(Modifier.PUBLIC)
                .addStatement("return String.format($S, id)", "https://sass-lang.com/d/%s")
                .returns(String.class)
                .build());


        JavaFile javaFile = JavaFile.builder("de.larsgrefer.sass.spec", enumBuilder.build()).build();

        javaFile.writeTo(getGeneratedSourcesDir().get().getAsFile());
    }

    private File getDeprecationsFile() {
        return getDeprecationsYamlFile().getAsFile().get();
    }

    @SuppressWarnings("NewApi")
    private Map<String, DeprecationDto> loadDeprecations() {

        YAMLMapper yamlMapper = new YAMLMapper();

        return yamlMapper.readValue(getDeprecationsFile(), new TypeReference<Map<String, DeprecationDto>>() {
        });
    }

    @Data
    public static class DeprecationDto {

        private String description;

        @JsonProperty("dart-sass")
        private DartSassDto dartSass;
    }

    @Data
    public static class DartSassDto {
        private String status;
        private String deprecated;
        private String obsolete;
    }
}
