plugins {
    id "java-gradle-plugin"
    id "io.freefair.lombok" version "9.8.0"
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'tools.jackson.dataformat:jackson-dataformat-yaml:3.2.3'
    implementation "com.palantir.javapoet:javapoet:0.20.0"
    implementation "io.freefair.okhttp:io.freefair.okhttp.gradle.plugin:9.8.0"
}

gradlePlugin {
    plugins {
        register('sass.deprecations') {
            implementationClass = 'de.larsgrefer.sass.gradle.SassDeprecationsPlugin'
        }
    }
}